/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import jazari.FactoryStrategies;

/**
 *
 * @author BAP1
 */
public class FrameDataSource extends javax.swing.JFrame {

    /**
     * Creates new form JDL
     */
    public FrameDataSource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radio_video = new javax.swing.JRadioButton();
        radio_camera = new javax.swing.JRadioButton();
        radio_folder = new javax.swing.JRadioButton();
        btn_execute = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        radio_csv = new javax.swing.JRadioButton();
        radio_arff = new javax.swing.JRadioButton();
        radio_url = new javax.swing.JRadioButton();
        radio_iot = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_comPort = new javax.swing.JTextField();
        txt_url = new javax.swing.JTextField();
        radio_image = new javax.swing.JRadioButton();
        radio_microphone = new javax.swing.JRadioButton();
        radio_leapmotion = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Choose Data Source Type");

        buttonGroup1.add(radio_video);
        radio_video.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_video.setText("Video File");
        radio_video.setEnabled(false);
        radio_video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_videoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_camera);
        radio_camera.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_camera.setSelected(true);
        radio_camera.setText("Camera");
        radio_camera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cameraActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_folder);
        radio_folder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_folder.setText("Class Folder");
        radio_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_folderActionPerformed(evt);
            }
        });

        btn_execute.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_execute.setText("Execute");
        btn_execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_executeActionPerformed(evt);
            }
        });

        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_prev.setText("<-- Prev");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_csv);
        radio_csv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_csv.setText("Csv");
        radio_csv.setEnabled(false);
        radio_csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_csvActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_arff);
        radio_arff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_arff.setText("Arff");
        radio_arff.setEnabled(false);
        radio_arff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_arffActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_url);
        radio_url.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_url.setText("URL");
        radio_url.setEnabled(false);
        radio_url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_urlActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_iot);
        radio_iot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_iot.setText("IOT_Sensor");
        radio_iot.setEnabled(false);
        radio_iot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_iotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usb Port");

        txt_comPort.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_comPort.setText("COM3");

        txt_url.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_url.setText("http:");

        buttonGroup1.add(radio_image);
        radio_image.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_image.setText("Image");
        radio_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_imageActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_microphone);
        radio_microphone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_microphone.setText("Microphone");
        radio_microphone.setEnabled(false);
        radio_microphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_microphoneActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_leapmotion);
        radio_leapmotion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_leapmotion.setText("Leapmotion Device");
        radio_leapmotion.setEnabled(false);
        radio_leapmotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_leapmotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_leapmotion)
                            .addComponent(radio_microphone)
                            .addComponent(jLabel5)
                            .addComponent(radio_folder)
                            .addComponent(radio_image)
                            .addComponent(radio_video))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_prev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_execute))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radio_camera)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radio_arff)
                                    .addComponent(radio_csv)
                                    .addComponent(radio_iot))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_comPort, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radio_url)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_url)))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(radio_camera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_leapmotion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(radio_microphone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_folder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_video)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radio_csv)
                        .addGap(4, 4, 4)
                        .addComponent(radio_arff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_url))
                    .addComponent(txt_url, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_iot, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_comPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_execute, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_videoActionPerformed
        Settings.data_source=enums.EnumDataSource.VIDEO;
    }//GEN-LAST:event_radio_videoActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        prev();
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_executeActionPerformed
        execute();
    }//GEN-LAST:event_btn_executeActionPerformed

    private void radio_cameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cameraActionPerformed
        Settings.data_source=enums.EnumDataSource.CAMERA;
    }//GEN-LAST:event_radio_cameraActionPerformed

    private void radio_microphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_microphoneActionPerformed
        Settings.data_source=enums.EnumDataSource.MICROPHONE;
    }//GEN-LAST:event_radio_microphoneActionPerformed

    private void radio_leapmotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_leapmotionActionPerformed
        Settings.data_source=enums.EnumDataSource.LEAP_MOTION;
    }//GEN-LAST:event_radio_leapmotionActionPerformed

    private void radio_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_folderActionPerformed
        Settings.data_source=enums.EnumDataSource.IMAGE_FOLDER;
    }//GEN-LAST:event_radio_folderActionPerformed

    private void radio_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_imageActionPerformed
        Settings.data_source=enums.EnumDataSource.IMAGE_FILE;
    }//GEN-LAST:event_radio_imageActionPerformed

    private void radio_csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_csvActionPerformed
        Settings.data_source=enums.EnumDataSource.CSV;
    }//GEN-LAST:event_radio_csvActionPerformed

    private void radio_arffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_arffActionPerformed
        Settings.data_source=enums.EnumDataSource.ARFF;
    }//GEN-LAST:event_radio_arffActionPerformed

    private void radio_urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_urlActionPerformed
        Settings.data_source=enums.EnumDataSource.URL;
    }//GEN-LAST:event_radio_urlActionPerformed

    private void radio_iotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_iotActionPerformed
        Settings.data_source=enums.EnumDataSource.IOT_SENSORS;
    }//GEN-LAST:event_radio_iotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDataSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDataSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDataSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDataSource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDataSource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_execute;
    private javax.swing.JButton btn_prev;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio_arff;
    private javax.swing.JRadioButton radio_camera;
    private javax.swing.JRadioButton radio_csv;
    private javax.swing.JRadioButton radio_folder;
    private javax.swing.JRadioButton radio_image;
    private javax.swing.JRadioButton radio_iot;
    private javax.swing.JRadioButton radio_leapmotion;
    private javax.swing.JRadioButton radio_microphone;
    private javax.swing.JRadioButton radio_url;
    private javax.swing.JRadioButton radio_video;
    private javax.swing.JTextField txt_comPort;
    private javax.swing.JTextField txt_url;
    // End of variables declaration//GEN-END:variables

    private void prev() {
        setVisible(false);
        StaticFrames.frmLearningMode.setVisible(true);
    }

    private void execute() {
        setVisible(false);
//        FactoryStrategies.execute();
    }
}
