/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import enums.EnumDevelopmentPlatform;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author BAP1
 */
public class FrameDevelopmentPlatform extends javax.swing.JFrame {

    /**
     * Creates new form JDL
     */
    public FrameDevelopmentPlatform() {
        initComponents();
//        addComponentListener(new ComponentAdapter() {
//            public void componentHidden(ComponentEvent e) {
//                /* code run when component hidden*/
//            }
//
//            public void componentShown(ComponentEvent e) {
//                initialize();
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radio_js = new javax.swing.JRadioButton();
        radio_python = new javax.swing.JRadioButton();
        radio_dl4j = new javax.swing.JRadioButton();
        btn_next = new javax.swing.JButton();
        radio_weka = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Choose Machine Learning Platform");

        buttonGroup1.add(radio_js);
        radio_js.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_js.setText("JavaScript");
        radio_js.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_jsActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_python);
        radio_python.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_python.setSelected(true);
        radio_python.setText("Python");
        radio_python.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pythonActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_dl4j);
        radio_dl4j.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_dl4j.setText("DL4J");
        radio_dl4j.setEnabled(false);
        radio_dl4j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dl4jActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_next.setText("Next  -->");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_weka);
        radio_weka.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radio_weka.setText("Weka");
        radio_weka.setEnabled(false);
        radio_weka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_wekaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_next)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radio_python)
                        .addComponent(radio_js)
                        .addComponent(radio_dl4j)
                        .addComponent(jLabel5)
                        .addComponent(radio_weka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(radio_python)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_js)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_dl4j)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_weka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_jsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_jsActionPerformed
        Settings.development_platform = enums.EnumDevelopmentPlatform.JAVA_SCRIPT;
    }//GEN-LAST:event_radio_jsActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        nextStep();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void radio_pythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pythonActionPerformed
        Settings.development_platform = enums.EnumDevelopmentPlatform.PYTHON;
    }//GEN-LAST:event_radio_pythonActionPerformed

    private void radio_dl4jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dl4jActionPerformed
        Settings.development_platform = enums.EnumDevelopmentPlatform.DL4J;
    }//GEN-LAST:event_radio_dl4jActionPerformed

    private void radio_wekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_wekaActionPerformed
        Settings.development_platform = enums.EnumDevelopmentPlatform.WEKA;
    }//GEN-LAST:event_radio_wekaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDevelopmentPlatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDevelopmentPlatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDevelopmentPlatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDevelopmentPlatform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDevelopmentPlatform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radio_dl4j;
    private javax.swing.JRadioButton radio_js;
    private javax.swing.JRadioButton radio_python;
    private javax.swing.JRadioButton radio_weka;
    // End of variables declaration//GEN-END:variables

    private void nextStep() {
        setVisible(false);
        StaticFrames.frmBackend.setVisible(true);
    }

    private void initialize() {
        if (Settings.development_platform == enums.EnumDevelopmentPlatform.PYTHON) {
            radio_python.setSelected(true);
        } else if (Settings.development_platform == enums.EnumDevelopmentPlatform.JAVA_SCRIPT) {
            radio_js.setSelected(true);
        } else if (Settings.development_platform == enums.EnumDevelopmentPlatform.DL4J) {
            radio_dl4j.setSelected(true);
        } else if (Settings.development_platform == enums.EnumDevelopmentPlatform.WEKA) {
            radio_weka.setSelected(true);
        }
    }
}
